server:
  port: 8090

spring:
  main:
    allow-circular-references: true
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/gittalentdb?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: 123456

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.ljh.pojo.entity
  configuration:
    map-underscore-to-camel-case: true

# 讯飞星火ai配置
xunfei:
  client:
    hostUrl: https://spark-api.xf-yun.com/v3.1/chat
    appid: fda7144c
    apiSecret: ODlmNjZiZWIyNTg1MzEzZjEwMTU4MWMw
    apiKey: f4fbf7d60421f7fa67ea8745a3666e46